services:
  - type: web
    name: econ-search-api
    env: python
    plan: free
    rootDir: econ-search-api
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -b 0.0.0.0:$PORT --timeout 120 app:app
    healthCheckPath: /health

